config/routes.rb
Mediapoints::Application.routes.draw do
  resources :videoassets

  devise_for :admins

    root 'videoassets#index'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mptype.rb
class Mptype < ActiveRecord::Base
  has_many :points
end

app/models/point.rb
class Point < ActiveRecord::Base
  validates :img , presence: true
  validates :ad_start , presence: true
  belongs_to :videoasset
  belongs_to :mptype
end

app/models/videoasset.rb
class Videoasset < ActiveRecord::Base
  validates :merlinid, presence: true
  self.primary_key = 'merlinid'
  has_many :points
  accepts_nested_attributes_for :points
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_filter :authenticate_admin!
end

app/controllers/videoassets_controller.rb
class VideoassetsController < ApplicationController
  before_action :set_videoasset, only: [:show, :edit, :update, :destroy]

  def index
    @videoassets = Videoasset.all
    respond_to do |format|
      format.html 
      format.json { render :json=>@videoassets}
      format.xml { render :xml=>@videoassets }
    end
  end

  def show
 json_string = render_to_string formats: :json    
 json_object = JSON.parse(json_string)     
 render :json => JSON.pretty_generate(json_object)
  end

  def new
    @videoasset = Videoasset.new
    @mptypes = Mptype.all.map { |t| [t.mptype,t.id] }
    @points = @videoasset.points.build
    
  end

  def edit
  end

  def create
    puts videoasset_params
    @current_asset =  Videoasset.find_by_merlinid(params[:videoasset][:merlinid])
    if @current_asset then
      @current_asset.points.create(params[:videoasset][:points_attributes]["0"])
      respond_to do |format|
          
          if @current_asset.save
            format.html { redirect_to @current_asset, notice: 'Videoasset was successfully created.'}
            format.json { render action: 'show', status: :created, location: @current_asset }
          end     
          
        end        
     else
      @videoasset = Videoasset.new(videoasset_params)
       respond_to do |format|     
      if @videoasset.save
        format.html { redirect_to @videoasset, notice: 'Videoasset was successfully created.' }
        format.json { render action: 'show', status: :created, location: @videoasset }
      else
        format.html { render action: 'new' }
        format.json { render json: @videoasset.errors, status: :unprocessable_entity }
      end
    end
    end
    
  end

  def update
    respond_to do |format|
      if @videoasset.update(videoasset_params)
        format.html { redirect_to @videoasset, notice: 'Videoasset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @videoasset.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @videoasset.destroy
    respond_to do |format|
      format.html { redirect_to videoassets_url }
      format.json { head :no_content }
    end
  end

  private
    def set_videoasset
      @videoasset = Videoasset.find(params[:id]) 
    end

    def videoasset_params
      params.require(:videoasset).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videoassets_helper.rb
module VideoassetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediapoints</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application","dynamic_form" "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <ul class="nav nav-pills pull-right">
      <% if admin_signed_in? %>
       <li><%= link_to "Sign out | #{current_admin.email}", destroy_admin_session_path, :method => :delete %></li>
       <% else %>
       <li><%= link_to "Sign in", new_admin_session_path %></li>
       <li><%= link_to "Sign up", new_admin_registration_path %></li>
     <% end %>
</ul>
    </div>
  </div>

<div class = "container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</div>

</body>
</html>

app/views/videoassets/_form.html.erb
  <div class="form">
<%= form_for(@videoasset) do |f| %>
  <% if @videoasset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@videoasset.errors.count, "error") %> prohibited this videoasset from being saved:</h2>

      <ul>
      <% @videoasset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :merlinid %><br>
    <%= f.number_field :merlinid %>
 
  <div class="points"> 
  <%= f.fields_for :points do |m| %>
  <%= m.label :mptype_id %><br>
  <%= m.select :mptype_id,@mptypes , {:prompt => 'Select One'},{:onchange => "get_dynamic_form(this)"} %>
  <div id = "itunes_form">
  	
<%= m.label :img %>
<%= m.text_field :img%><br>
<%= m.label :title%>
<%= m.text_field :title%><br>
<%= m.label :artist%>
<%= m.text_field :artist%><br>
<%= m.label :price%>
<%= m.text_field :price%><br>
<%= m.label :launchLink%>
<%= m.text_field :launchLink%><br>
  	
  </div>
  <div id  = "ad_form">
  <%= m.label :ad_start%>
  <%= m.text_field :ad_start%></br>   
  <%= m.label :ad_duration %>
  <%= m.text_field :ad_duration%></br>
  <%= m.label :ad_url%>
  <%= m.text_field :ad_url %>
  </div>  

  	
  	
  	<%end%>
  	
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
   </div>
<% end %>

app/views/videoassets/_mptype.html.erb
<%= m.label :img %>
<%= m.text_field :img%><br>
<%= m.label :title%>
<%= m.text_field :title%><br>
<%= m.label :artist%>
<%= m.text_field :artist%><br>
<%= m.label :price%>
<%= m.text_field :price%><br>
<%= m.label :launchLink%>
<%= m.text_field :launchLink%><br>

app/views/videoassets/edit.html.erb
<h1>Editing videoasset</h1>

<%= render 'form' %>

<%= link_to 'Show', @videoasset %> |
<%= link_to 'Back', videoassets_path %>

app/views/videoassets/index.html.erb
<h1>Listing videoassets</h1>

<table>
  <thead>
    <tr>
      <th>Merlinid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videoassets.each do |videoasset| %>
      <tr>
        <td><%= videoasset.merlinid %></td>
        <td><%= link_to 'Show', videoasset %></td>
        <td><%= link_to 'Edit', edit_videoasset_path(videoasset) %></td>
        <td><%= link_to 'Destroy', videoasset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Videoasset', new_videoasset_path %>

app/views/videoassets/new.html.erb
<h1>New videoasset</h1>

<%= render 'form' %>

<%= link_to 'Back', videoassets_path %>

app/views/videoassets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Merlinid:</strong>
  <%= @videoasset.merlinid %>
</p>
<%= params.inspect%>
<%= link_to 'Edit', edit_videoasset_path(@videoasset) %> |
<%= link_to 'Back', videoassets_path %>